### ISSUE TITLE
Bug for php 5.6

### ISSUE THREAD

**Issue by micayael** [intriro/csv-bundle#3]
Hi

Are you aware of this: https://github.com/goodby/csv/issues/60

I think a good idea to create a tag here too.

**Comment by alsar** [comment]
I rather not require dev-master within stable releases, so I created a fix for those that are using the affected PHP versions. 
For this bug I created a new branch and loosen the version constraint. Please add this to your composer.json:

``` json
    "intriro/csv-bundle": "dev-php-5.6-hotfix",
    "goodby/csv": "dev-master"
```

This is a temporal fix until a new version of goodby/csv is released.

**Comment by micayael** [comment]
Thanks @alsar.

**Comment by alsar** [comment]
Closing as it was fixed and a new version released.
